### ISSUE TITLE
Error using with cordova 5.3.3

### ISSUE THREAD

**Issue by ghost** [brodysoft/Cordova-SQLitePlugin-2014.07#2]
error: cannot find symbol
                this.sendJavascriptCB("window.SQLitePluginCallback.p1('" + id +
"', " + result + ");");
                                                                           ^
  symbol:   variable id
  location: class SQLitePlugin
Note: \platforms\android\src\org\pgsqlite\SQLitePlugin.java
 uses or overrides a deprecated API.

**Comment by brody2consult** [comment]
This version is no longer supported. Please use one of these versions:
- https://github.com/litehelpers/Cordova-sqlite-storage
- https://github.com/litehelpers/cordova-sqlite-ext

**Comment by ghost** [comment]
Thanks
