### ISSUE TITLE
Getting "id" variable issue in pgsqlite plugin for Cordova app.

### ISSUE THREAD

**Issue by NileshSystematix** [brodysoft/Cordova-SQLitePlugin-2014.07#3]
I have created one Cordova app project for android platform whose details are as follows:

Cordova version---- 6.3.1
Android version------ 4.1.1

I have add "pgsqlite" plugin in the project after that I am getting "id" issue in the SQLitePlugin.java in the below line: 

this.sendJavascriptCB("window.SQLitePluginCallback.p1('" + id + "', " + result + ");");

and the error  is "id cannot be resolved to a variable".

It was working fine with the older version of Cordova.

Please find me some solution.

**Comment by brody2consult** [comment]
This plugin version is no longer supported. Please try https://github.com/litehelpers/Cordova-sqlite-storage.
